### Suru Theme
## Author: Wei-Ying Chen
# URL: https://github.com/sainnhe/sonokai
## Colors palette
# URL: https://snwh.org/suru/guidelines
# License: MIT License

"type" = "blue"
"constant" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "orange"
"string" = "yellow"
"comment" = "grey"
"variable" = "fg"
"variable.builtin" = "orange"
"variable.parameter" = "fg"
"variable.other.member" = "fg"
"label" = "orange"
"punctuation" = "grey"
"punctuation.delimiter" = "grey"
"punctuation.bracket" = "fg"
"keyword" = "red"
"operator" = "orange"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "purple"
"tag" = "yellow"
"namespace" = "blue"
"attribute" = "purple"
"constructor" = "blue"
"module" = "blue"
"special" = "orange"

"markup.heading.marker" = "grey"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "grey"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

"ui.background" = { bg = "bg0" }
"ui.cursor" = { modifiers = ['reversed'] }
"ui.cursor.match" = { fg = "orange", bg = "orange" }
"ui.cursor.insert" = { fg = "black", bg = "grey" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.selection" = { bg = "bg5" }
"ui.selection.primary" = { bg = "bg4" }
"ui.linenr" = "grey"
"ui.linenr.selected" = "fg"
"ui.cursorline.primary" = { bg = "bg1" }
"ui.statusline" = { fg = "fg", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey", bg = "bg1" }
"ui.popup" = { fg = "grey", bg = "bg2" }
"ui.window" = { fg = "grey", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = "fg"
"ui.text.focus" = "green"
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.whitespace" = { fg = "grey_dim" }
"ui.virtual.ruler" = { bg = "grey_dim" }

info = { fg = 'green' }
hint = { fg = 'blue' }
warning = { fg = 'orange' }
error = { fg = 'red' }

"diagnostic.info" = { underline = { style = "curl", color = "green" } }
"diagnostic.hint" = { underline = { style = "curl", color = "blue" } }
"diagnostic.warning" = { underline = { style = "curl", color = "orange" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }

[palette]
black = "#181818"
bg0 = "#242424" # black
bg1 = "#333333"
bg2 = "#363636"
bg3 = "#3b3b3b"
bg4 = "#5c5c5c"
bg5 = "#444444"
fg = "#e3dfd5" # white
red = "#f34f17" # orange
orange = "#fda463" # light orange
yellow = "#46a926" # green
green = "#d85eca" # violet
blue = "#2daaaa" # turquoise
purple = "#8f76e4" # purple
grey = "#7f7f7f"
grey_dim = "#595959"
